# Generated by Django 4.1.3 on 2022-11-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Name')),
                ('date', models.DateTimeField(max_length=20, verbose_name='Time')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('email', models.TextField(max_length=320, verbose_name='Feedback')),
                ('group', models.CharField(max_length=100, verbose_name='Group of Servers')),
                ('stype', models.CharField(max_length=30, verbose_name='Type of group')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
            ],
        ),
    ]
